### ISSUE TITLE
Shorthand flag for help command `-h` results in "Invalid Profile" warning

### ISSUE THREAD

**Issue by masamerc** [pjaudiomv/awsd#20]
## Overview
`help` command suggests users can supply `-h` flag to see the help message but `-h` results in a warning

### Environment
- awsd version: `v0.0.8`
- os: Mac OSX 13.6.3 (22G436) 

### Current behavior
Running `$ _awsd -h` results in the following error
```
WARNING: Profile -h does not exist.
```
![demo](https://github.com/radiusmethod/awsd/assets/24425632/66ff3268-7dae-428b-96bf-7daf55518785)

However the current help command suggests `-h` flag is available.
```
Flags:
  -h, --help   help for awsd
```
```
$ _awsd help
Allows for switching AWS profiles files.

Usage:
  awsd [flags]
  awsd [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  list        List AWS profiles command.
  version     awsd version command

Flags:
  -h, --help   help for awsd 

Use "awsd [command] --help" for more information about a command.
```

## Expected behavior
`-h` shorthand flag behaves the same way as `help` command and `--help` flag

**Comment by pjaudiomv** [comment]
resolved by https://github.com/radiusmethod/awsd/pull/21
